#!/bin/bash
set -ue

REPO_ROOT="$(git rev-parse --show-toplevel)"
HOOKS_DIR="$REPO_ROOT/.git/hooks"
PRE_COMMIT_HOOK="$HOOKS_DIR"/pre-commit
CI_DIR="$REPO_ROOT"/CI
VIRTUALENV_DIR="$REPO_ROOT/.virtualenv"
FORMAT_STAGED_SCRIPT="$CI_DIR"/format-staged
REQUIREMENTS_TXT="$REPO_ROOT"/requirements.txt

# Re-init hooks directory
rm -r "$HOOKS_DIR" || true
mkdir -p "$HOOKS_DIR"

# Install pre-commit hook
cat > "$PRE_COMMIT_HOOK" <<EOF
#!/bin/bash
"$FORMAT_STAGED_SCRIPT"
EOF
chmod u+x "$PRE_COMMIT_HOOK"

# Re-create python virtualenv with dependencies
if command -v deactivate 2>/dev/null; then 
    deactivate
fi
rm -r "$VIRTUALENV_DIR" 2>/dev/null || true
virtualenv -p "$(command -v python3)" "$VIRTUALENV_DIR"
# shellcheck disable=SC1091
source .virtualenv/bin/activate
pip install --upgrade pip
pip install -r "$REQUIREMENTS_TXT"
deactivate

