#!/bin/bash

REPO_ROOT="$(git rev-parse --show-toplevel)"
VIRTUALENV_DIR="$REPO_ROOT/.virtualenv"

if [ -f "$VIRTUALENV_DIR"/bin/activate ]
then
    # shellcheck disable=SC1091
    . "$VIRTUALENV_DIR"/bin/activate
else
    echo "virtualenv not configured. Did you forget to invoke ./config?"
fi


# shellcheck disable=SC2139
alias build="(cd ""$REPO_ROOT""/2022/seb && make)"