#!/bin/bash -eu

REPO_ROOT="$(git rev-parse --show-toplevel)"
REPO_CHORES_DIR="$REPO_ROOT/.repo-chores"
REPO_CHORES_GIT_DIR="$REPO_CHORES_DIR/git"
REPO_CHORES_MD_DIR="$REPO_CHORES_DIR/md"
VIRTUALENV_DIR="$REPO_CHORES_DIR/.virtualenv"

# shellcheck disable=SC1091
. "$VIRTUALENV_DIR"/bin/activate

STAGED_FILES="$("$REPO_CHORES_GIT_DIR"/diff-list-cached-acmr '*.md')"
UNSTAGED_FILES="$("$REPO_CHORES_GIT_DIR"/diff-list-acmr '*.md')"

[ -z "$STAGED_FILES" ] && exit 0

if [[ $(comm -3 --total <(echo "$STAGED_FILES" | sort) <(echo "$UNSTAGED_FILES" | sort) | wc -c) -ne 0 ]]
then
    echo "Some of your staged files need formatting but you have unstaged changes."
    echo "Stage your changes before committing to prevent your unstaged changes to be overriden"
    exit 1
fi

echo "Formatting staged files..."
echo "$STAGED_FILES" | xargs "$REPO_CHORES_MD_DIR"/format

echo "Embedding code in code-blocks..." 
echo "$STAGED_FILES" | xargs -I "$REPO_CHORES_MD_DIR"/embed-code-blocks {}

echo "Staged markdown files have been formatted. Verify the changes, stage the files and re-attempt the commit"
exit 1