#!/bin/sh
FILES=$(git diff --cached --name-only --diff-filter=ACMR -- '*.md' | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

echo "Running md-format on files"

# Run md-format on all selected files
echo "$FILES" | xargs -I{} mdformat {}

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add

exit 0