#!/bin/sh
FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

# Run md-format on all selected files
echo "$FILES" | mdformat

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add

exit 0