#!/bin/bash
# Produce a ledger formatted CSV from a SEB Account XLSX

# JQ Expressions
JQ_SET_CURRENCY='.[].amount |= (. | tostring + "SEK") | .[].balance |= (. | tostring + " SEK")'
JQ_STRIP_DESC_DATES_AND_SPACES='.[].desc |= sub("\\s*/.*$";"")'

# Convert XLSX to CSV
# Remove useless lines
# Prepend ledger convert header
#   Known ledger convert headers are date, posted, code, payee or desc or description, amount, 
#   cost, total, and note
#   https://www.ledger-cli.org/3.0/doc/ledger3.html#The-convert-command
# Convert to JSON
# Set commodity
# Clean-up description field
# Convert to CSV

in2csv $1                                                              \
    | sed '1,/Bokföringsdatum/d'                                       \
    | cat <(echo "date,currency_date,transid,desc,amount,balance") -   \
    | csvjson                                                          \
    | jq "$JQ_SET_CURRENCY"                                            \
    | jq "$JQ_STRIP_DESC_DATES_AND_SPACES"                             \
    | in2csv -f json                                                   \